
version: 2

models:

    - name: dim_risk
      description: "Risk Dimension"
      columns:
        - name: risk_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null
    
    - name: dim_insured_line
      description: "Insured Line Dimension"
      columns:
        - name: insured_line_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: stg_fct_written_transactions
      description: "Staging for Written Transactions"

    - name: dim_date
      description: "Date Dimension"

    - name: stg_policies
      description: "Policy Stage"

    - name: stg_policy_settlement_sched_deduction_full
      description: "Sched Deductions Combined"
    
    - name: stg_policy_settlement_sched_deduction_share
      description: "Deduction Line Shares"

    - name: stg_policy_settlement_sched_full
      description: "Schedule Premium Combined"

    - name: stg_policy_settlement_sched_deduction
      description: "Premium Line Share"

    - name: stg_policy_settlement_sched_share
      description: "Deductions Schedule"

    - name: stg_policy_settlement_sched
      description: "Policy Premium Schedule"

    - name: stg_policy_settlement_union
      description: "Union of Premium & Deduction"

    - name: stg_policylines
      description: "Lines"

    - name: stg_policyprem
      description: "Policy Premium"

    - name: dim_parties
      description: "Parties Dimension"
      columns:
        - name: party_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null
    
    - name: fct_transactions
      description: "Transaction Fact"
      columns:
        - name: transaction_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: fct_periodic_premium_snapshot
      description: "A Summarised Premium Snapshot"
      columns:
        - name: periodic_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null