
version: 2

models:

    - name: dim_risk
      description: "Risk Dimension"
      columns:
        - name: risk_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null
    
    - name: dim_insured_line
      description: "Insured Line Dimension"
      columns:
        - name: insured_line_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: dim_claims
      description: "Claim Dimension"
      columns:
        - name: claim_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: dim_financial_categories
      description: "Financial Category Dimension"
      columns:
        - name: financial_category_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: dim_loss_events
      description: "Loss Events Dimension"
      columns:
        - name: loss_event_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: dim_transaction_events
      description: "Transactional Events Dimension"
      columns:
        - name: transaction_event_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: dim_parties
      description: "Parties Dimension"
      columns:
        - name: party_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null
    
    - name: fct_transactions
      description: "Transaction Fact"
      columns:
        - name: transaction_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: fct_periodic_premium_snapshot
      description: "A Summarised Premium Snapshot"
      columns:
        - name: periodic_key
          description: "The primary key for this table"
          tests: 
            - unique
            - not_null

    - name: stg_nonbureau_booked_premdeduct_alldays
      description: "A Summarised Premium Snapshot"
      columns:
        - name: dupe_checker
          description: "A checker to see if I've messed up."
          tests: 
            - unique
            - not_null